### ISSUE TITLE
Top margin

### ISSUE THREAD

**Issue by sedghi** [ChrisDienes/latex_resume#1]
Hi,
Thanks for the template, it loos great. 
Could you please clarify how I can change the top margin? I tried different syntax but none of them work

Thanks

**Comment by ChrisDienes** [comment]
Sorry I wasn't watching this repo and missed your issue. Did you find a solution to your top margin question?

**Comment by sedghi** [comment]
Not yet

**Comment by ChrisDienes** [comment]
If you want to change the topmargin size:
Start by downloading all the repo files and save them in the same folder (I assume you already did this). If you're using R/RStudio, then the main file you'll open and edit is resume.Rnw which uses the R Sweave framework. If you're not using the R Sweave approach, but rather pure latex, then the file will be resume.tex.   The top lines of these files define some basic document settings. For example, line 8 has: \parsep=0in. If you insert a new statement on line 9 such as \topmargin=-0.5in or \topmargin=10in, you'll see drastic changes to the topmargin size. 

If you want to change the content of the topmargin header: 
Do a search (Ctrl+f) for "\name" in either resume.Rnw (R sweave) or resume.tex (pure latex), should be around lines 26/27 in my files. This line can be changed to be your name and occupation. Try commenting out my \name{...} statement, and then modify a copied version with your values. You will likely need to adjust the \hspace{243pt} statement to meet your needs (i.e. increase or decrease 243).
